package util;

public enum TipoToken {
  PALAVRA_RESERVADA,
  IDENTIFICADOR,
  NUMERO_INTEIRO,
  NUMERO_REAL,
  OPERADOR_ARITMETICO,
  OPERADOR_RELACIONAL,
  OPERADOR_LOGICO,
  SIMBOLO_ESPECIAL,
  ATRIBUICAO,
  FIM
}
